print('             _____ ')
print('            |     |')
print('            | Hi! |')
print('       @@@  |_   _|')
print('     @     @  | /')
print('     @     @  |/')
print('       @@@')
print('        @      @')
print('       @@@    @')
print('      @ @ @  @')
print('     @  @  @@')
print('    @   @')
print('   @    @')
print('  @     @')
print('        @')
print('       @ @')
print('      @   @')
print('     @     @')
print('    @       @')
print('   @         @')
print('  @           @')
print('@@             @@')
